module.exports = {
  HEADLINE_MAX: 30,
  DESCRIPTION_MAX: 90,
  KEYWORD_MAX: 80,
  MIN_HEADLINES: 3,
  MIN_DESCRIPTIONS: 2,
  STATUS: { ENABLED: 2, PAUSED: 3 },
  STATUS_LABEL: { 2: "ON", 3: "PAUSED" },
  MATCH_TYPE_LABEL: { 2: "EXACT", 3: "PHRASE", 4: "BROAD" },
};
